// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM5qEblvMd8rjUnn33-Qfxh7lNA1ZScY4',
    appId: '1:457086562741:web:d976b6fc0647ea5ce169fc',
    messagingSenderId: '457086562741',
    projectId: 'fir-first-app-519aa',
    authDomain: 'fir-first-app-519aa.firebaseapp.com',
    databaseURL: 'https://fir-first-app-519aa-default-rtdb.firebaseio.com',
    storageBucket: 'fir-first-app-519aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdQ09kQgt7uYRsv-T322di1PXA1NONYfo',
    appId: '1:457086562741:android:627bbfb81089e0f0e169fc',
    messagingSenderId: '457086562741',
    projectId: 'fir-first-app-519aa',
    databaseURL: 'https://fir-first-app-519aa-default-rtdb.firebaseio.com',
    storageBucket: 'fir-first-app-519aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWkfAM4iI23jUekTxd8YMwf8o0Q5gLqIU',
    appId: '1:457086562741:ios:3473034e2e055033e169fc',
    messagingSenderId: '457086562741',
    projectId: 'fir-first-app-519aa',
    databaseURL: 'https://fir-first-app-519aa-default-rtdb.firebaseio.com',
    storageBucket: 'fir-first-app-519aa.appspot.com',
    iosBundleId: 'com.example.loginSignupFirebase',
  );
}
